# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12f68aa9b4f62fc772281e3763ed6815bed900843e4257641d2bc366110eadb5c7aaa9f2484384b16f1d843e87ceadc6e50274119439e8fa9148d8d1fc5ba136

test:
  secret_key_base: 0ec8979da8c44e9513e399ee7174558f0560257ada18cf4d01704f591868d8273f16cda6d0a669dd9a1bbeb959114f2dfc859088195ed8ec6a249fabfde96ad2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
